config/routes.rb
Appr::Application.routes.draw do
  devise_for :users
  resources :sprints

  root 'application#index'

  resources :tasks do
  end
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  has_many :tasks
end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
  has_many :tasks

  validates_presence_of :startdate, :enddate, :name
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :priority
  belongs_to :user
  belongs_to :sprint

  validates_presence_of :name, :priority_id
  validates_numericality_of :estimation, :allow_nil => true, :only_integer => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks

  def full_name
    [self.first_name, self.prefix, self.last_name].reject(&:blank?).join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  def index

  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_sprint, only: [:show, :edit, :update, :destroy]

  def index
    @sprints = Sprint.all
  end

  def show
  end

  def new
    @sprint = Sprint.new
  end

  def edit
  end

  def create
    @sprint = Sprint.new(sprint_params)

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to @sprint, notice: 'Sprint was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sprint }
      else
        format.html { render action: 'new' }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sprint.update(sprint_params)
        format.html { redirect_to @sprint, notice: 'Sprint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sprint.destroy
    respond_to do |format|
      format.html { redirect_to sprints_url }
      format.json { head :no_content }
    end
  end

  private

    def set_sprint
      @sprint = Sprint.find(params[:id])
    end

    def sprint_params
      params.require(:sprint).permit(:startdate, :enddate, :name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!

  before_filter :new_task, only: [:new, :create]
  before_filter :load_task, only: [:show, :update, :edit, :destroy]

  def index
    @tasks = Task.all
  end

  def new
  end

  def create
    if @task.save
      redirect_to :action => 'index'
    else
      render :new
    end
  end

  def show
  end

  def update
    if @task.update_attributes(task_params)
      redirect_to :action => 'index'
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @task.destroy

    redirect_to :action => 'index'
  end

  protected

    def new_task
      p = task_params unless !params[:task]
      @task = Task.new(p)
    end

    def load_task
      @task = Task.find(params[:id])
    end

  private

    def task_params
      params.require(:task).permit(:name, :priority_id, :user_id, :estimation, :sprint_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/index.html.haml
%h1.title ApproXIV Management Dashboard

.menu
  = render_navigation

.navigation
  .nav-item
    %h2= link_to 'Tasks', tasks_path
    - tasks = {total: Task.all.count, critical: Task.where(:priority_id => 4).count, high: Task.where(:priority_id => 3).count, medium: Task.where(:priority_id => 2).count, low: Task.where(:priority_id => 1).count}
    %p
      Tasks:
      = tasks[:total]
    .status{data: {'total-tasks' => tasks[:total]}}
      .prio-critical{data: {'tasks' => tasks[:critical]}}
        = tasks[:critical]
      .prio-high{data: {'tasks' => tasks[:high]}}
        = tasks[:high]
      .prio-medium{data: {'tasks' => tasks[:medium]}}
        = tasks[:medium]
      .prio-low{data: {'tasks' => tasks[:low]}}
        = tasks[:low]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApproXIV Management</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}
  %ul
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/sprints/_form.html.haml
= simple_form_for @sprint do |f|
  = f.error_notification

  = f.input :startdate
  = f.input :enddate

  = f.input :name

  = f.collection_check_boxes :task_ids, Task.all, :id, :name, {class: 'select2'})

  = f.button :submit

app/views/sprints/edit.html.haml
%h1 Editing sprint

= render 'form'

= link_to 'Show', @sprint
= link_to 'Back', sprints_path

app/views/sprints/index.html.haml
%h1 Listing sprints

%table.table.table-striped
  %thead
    %tr
      %th Startdate
      %th Enddate
      %th Name
      %th Tasks
      %th{colspan: 3} Actions
  %tbody
    - @sprints.each do |sprint|
      %tr
        %td= sprint.startdate
        %td= sprint.enddate
        %td= sprint.name
        %td= sprint.tasks.count
        %td= link_to 'Show', sprint
        %td= link_to 'Edit', edit_sprint_path(sprint)
        %td= link_to 'Destroy', sprint, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Sprint', new_sprint_path

app/views/sprints/new.html.erb
<h1>New sprint</h1>

<%= render 'form' %>

<%= link_to 'Back', sprints_path %>

app/views/sprints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Startdate:</strong>
  <%= @sprint.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @sprint.enddate %>
</p>

<%= link_to 'Edit', edit_sprint_path(@sprint) %> |
<%= link_to 'Back', sprints_path %>

app/views/tasks/_form.html.haml
= simple_form_for @task do |f|
  = render 'shared/error_messages', object: f.object

  %p
    = f.input :name

  %p
    = f.label :priority_id
    = f.select(:priority_id, Priority.all.collect {|p| [ p.name, p.id ] }, {}, {:class => 'select2', :prompt => true})

  %p
    = f.label :user_id
    = f.select(:user_id, User.all.collect {|p| [ p.full_name, p.id ] }, {}, {:class => 'select2', :prompt => true})

  %p
    = f.label :sprint_id
    = f.select(:sprint_id, Sprint.all.collect {|s| s.name }, {}, {:class => 'select2', :promt => true})

  %p
    = f.input :estimation

  %p
    = f.input :description

  = link_to 'Cancel', tasks_path, class: 'btn'
  = f.button :submit, class: 'btn btn-primary'

app/views/tasks/edit.html.haml
%h1.title ApproXIV Management Edit Task: #{@task.name}

%p
  = link_to icon('arrow-circle-left') + " back", tasks_path

%content
  = render 'form'

app/views/tasks/index.html.haml
%h1.title ApproXIV Management Tasks

%p
  = link_to icon('arrow-circle-left') + " Home", root_path

%table.table.table-striped.table-bordered.tablesorter
  %thead
    %tr
      %th Name
      %th Priority
      %th Assignee
      %th Sprint
      %th Estimation
      %th Actions
  %tbody
    - @tasks.each do |task|
      %tr
        %td= link_to task.name, task_path(task.id)
        %td= task.priority.name unless !task.priority
        %td
          - if task.user
            = task.user.full_name
          - else
            = simple_form_for task do |f|
              = f.select(:user_id, User.all.collect {|p| [ p.full_name, p.id ] }, {}, {:class => 'select2', :prompt => true})
              = f.button :submit, 'Save', :class => 'btn btn-primary'
        %td= task.sprint.name unless !task.sprint
        %td= task.estimation
        %td
          = link_to 'Edit', edit_task_path(task.id), class: 'btn btn-primary'
          = link_to 'Delete', task_path(task.id), class: 'btn btn-danger', :confirm => 'Are you sure?', :method => :delete

= link_to "New task", new_task_path, class: "btn btn-primary"

app/views/tasks/new.html.haml
%h1.title ApproXIV Management New Task

%p
  = link_to icon('arrow-circle-left') + " back", tasks_path

%content
  = render 'form'

app/views/tasks/show.html.haml
%h1.title ApproXIV Management Task: #{@task.name}

%p
  = link_to icon('arrow-circle-left') + " back", tasks_path

%p
  Show